tasks/urls.py
from django.conf.urls.defaults import *
from django.views.generic.simple import *
from django.contrib import admin


# TODO
# Caution : Any non-matched url goes straight to display_portal and
# gives an error since a user of that name would not be found.
urlpatterns = patterns('tasks.views',
      (r'^$', 'display_portal'),
      (r'^create', 'edit_task'),
      (r'^task/(?P<task_id>[0-9]+)', 'edit_task'),
      (r'^display_task/(?P<task_id>[0-9]+)?', 'display_task'),
      (r'^subtask/(?P<subtask_id>[0-9]+)', 'edit_subtask'),
      (r'^display_subtask/(?P<subtask_id>[0-9]+)?', 'display_subtask'),
      (r'^department/(?P<department_name>\w+)?$', 'display_department_portal'),
      (r'^testform/(?P<task_id>[0-9]+)$', 'edit_task_subtasks'),
      (r'^documents/$', 'handle_documents'),

      # (r'^(\w+)?$', 'display_portal'),
)

urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin
from erp_test.tasks.views import *
from erp_test.users.views import *
from erp_test.home.views import *
from erp_test.finance.views import *
from erp_test.qms_barcode.views import *



# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',

    (r'^erp_test/$', include('qms_barcode.urls')),
    (r'^erp_test/home/',include('home.urls')),
    (r'^erp_test/users/', include('users.urls')),
    (r'^erp_test/participant/', include('qms_barcode.urls')),
    (r'^erp_test/(?P<owner_name>\w+)/finance/', include('finance.urls')),                       
    #(r'^dashboard/',include('dashboard.urls')),	
    # Make the above 2 URLConfs look like these 2 below
    (r'^erp_test/(?P<owner_name>\w+)/users/', include('users.urls')),
    (r'^erp_test/(?P<owner_name>\w+)/dashboard/',include('dashboard.urls')),	
    (r'^erp_test/(?P<owner_name>\w+)/', include('tasks.urls')),
    #(r'^now/sign.html$', sign_in, ),
    # Examples:
    # url(r'^$', 'erp_test.views.home', name='home'),
    # url(r'^', include('foo.urls')),
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    # Uncomment the next line to enable the admin:
    url(r'erp_test/^admin/', include(admin.site.urls)),
)

tasks/models.py
from django.db import models
from django.contrib.auth.models import User
from erp_test import settings
from erp_test.users.models import Group, Label
from erp_test.misc.helper import is_core, is_coord, get_page_owner, get_file_path
import os

# Create your models here.
#The choices may be cup level but if any thing better pls do change.
STAT_CHOICES= (
	('Open','Open'),
	('Completed','Completed'),
	('Late','Overdue'),
	('Almost Completed','Almost'),
)

DEFAULT_STATUS = 'Open'

doc_label_list = [ 'TeamDetails',
                   'DepartmentManual',
                   'MinutesOfMeeting',
                   'DepartmentPolicies',
                   'DepartmentReport',
                   'PreviousYearFeedback',
                   'OtherDocuments']

doc_heading_list = [ 'Team Details',
                     'Department Manual',
                     'Minutes Of Meeting',
                     'Department Policies',
                     'Department Report',
                     'Previous Year Feedback',
                     'Other Documents']

class AbstractBaseTask(models.Model):
    """
    Abstract Base Class for Task, SubTask.

    TODO:
    * File upload
    * Draft saving
    * QMS Manager for the Task
    """
    subject       = models.CharField(max_length=100 , null=True)
    description   = models.TextField(null=True , blank=True)
    creator       = models.ForeignKey(User, related_name = '%(app_label)s_%(class)s_creator')
    creation_date = models.DateTimeField (auto_now = True, editable = False)
    deadline      = models.DateField(null=True , blank=True)
    status        = models.CharField(max_length=20, choices=STAT_CHOICES,default = DEFAULT_STATUS)	

    
    class Meta:
        abstract = True
        
class Task(AbstractBaseTask):

    """
    Task Model

    Note : The department where the Task originated is understood from
    the Creator's department. As of now, only Cores can create Tasks.

    A Task mainly consists of SubTasks which are created and assigned by the respective Cores of each department.
    """
    # tags = models.ManyToManyField (Tag, blank = True)
    def is_owner (self, user):
        """
        user is the owner of the current Task if
        - user is a Core in the Task's department
        """
        print 'User Dept : ', user.get_profile ().get_dept ().name
        print 'Is Core : ', is_core (user)
        print 'Task Dept : ', self.creator.get_profile ().get_dept ().name
        return user.get_profile ().get_dept () == self.creator.get_profile ().get_dept () and is_core (user)

    def __str__(self):
        return str (self.subject)

    class Admin:
        pass

class SubTask(AbstractBaseTask):
    """
    SubTask Model

    As of now, SubTasks can be created mainly in two places :

    * When a Core breaks Tasks down into SubTasks and assigns some of
      them to Coords in his own department and/or delegates a SubTask
      to another Department (whose core has to then assign that
      SubTask to that department's coords, possibly creating more
      SubTasks as required)

    * When a Coord creates goals with deadlines for himself (these are
      called SubTasks but will actually be shown in his Timeline and
      handled differently from SubTasks that have been assigned to him
      by Cores)
    """
    coords = models.ManyToManyField (User, blank = True)
    department = models.ForeignKey (Group)
    task = models.ForeignKey (Task)

    def is_owner (self, user):
        """
        user is the owner of the current SubTask if
        - user is a Core in the department which created the Task
          which SubTask is related to
        - user is a Core in the department to which SubTask is assigned
        """
        print 'User Dept : ', user.get_profile ().get_dept ()
        print 'Is Core : ', is_core (user)
        print 'Task Dept : ', self.task.creator.get_profile ().get_dept ()
        print 'SubTask Dept : ', self.department
        user_dept = user.get_profile().get_dept ()
        return is_core (user) and (
            (user_dept == self.task.creator.get_profile ().get_dept ()) or
            (user_dept == self.department))

    def is_assignee (self, user):
        """
        Return True if user is a Coord who has been assigned this subtask.
        """
        print 'User Dept : ', user.get_profile ().get_dept ()
        print 'Is Coord : ', is_coord (user)
        user_dept = user.get_profile().get_dept ()
        return is_coord (user) and (self.coords.filter (id = user.id).exists ())

    def __str__(self):
        return str (self.subject)

    class Admin:
        pass

class Tag (models.Model):
    name = models.CharField (max_length = 100, blank = True)
    task = models.ManyToManyField (Task, blank = True)
    
    def __str__(self):
        return self.name

class AbstractComment (models.Model):
    """
    Abstract Base Class to store a comment.

    Timestamp helps to order comments. It is generated automatically.
    Author can be used to select particular comments based on the author.
    """
    author = models.ForeignKey (User, related_name = '%(app_label)s_%(class)s_author')
    comment_string = models.TextField ()
    time_stamp = models.DateTimeField (auto_now = True, editable = False)

    class Meta:
        abstract = True
        ordering = ['time_stamp']

class TaskComment(AbstractComment):
    """
    Comment written for a Task.
    """
    task = models.ForeignKey (Task)

    def __str__(self):
        return '%s %s' %(self.task.subject, self.id)
    class Admin:
        pass
        
        
class SubTaskComment(AbstractComment):
    """
    Comment written for a SubTask
    """
    subtask = models.ForeignKey (SubTask)

    def __str__(self):
        return '%s %s' %(self.subtask.subject, self.id)
    class Admin:
        pass
    
class Update (AbstractComment):
    """
    Used by Coord to send updates to a Core
    """
    class Admin:
        pass

class Document (models.Model):
    """
    Class for file upload.
    """
    document = models.FileField (upload_to = get_file_path, blank = True)
    uploader = models.ForeignKey (User)
    upload_date = models.DateTimeField (auto_now = True, editable = False)
    description = models.CharField(max_length = 100, blank = True)
    label = models.ForeignKey (Label, blank = True, null = True)

    def __str__(self):
        if self.document is not None:
            return '%s' % (os.path.basename (self.document.name))
        else:
            return 'Empty Doc'

    def get_document_heading (self):
        """
        Return heading for the Document.
        """
        heading_dict = dict (zip (doc_label_list, doc_heading_list))
        if self.label is not None:
            return heading_dict[self.label.name]
        else:
            return ''
        
    def get_google_docs_path (self):
        """
        Return link to Google Docs page for viewing current Document.
        """
        return ("http://docs.google.com/viewer?url=" +
                settings.MEDIA_URL + self.document.name)

# NOTE : Later, remove TaskDocument and SubTaskDocument models and
# simply have 'Task' and 'SubTask' as Labels

class TaskDocument (Document):
    """
    File upload for a Task.
    """
    task = models.ForeignKey (Task)
        
    # def __str__(self):
    #     return '%s' % (os.path.basename (self.document.name))


class SubTaskDocument (Document):
    """
    File upload for a SubTask.
    """
    subtask = models.ForeignKey (SubTask)
        
    # def __str__(self):
    #     return '%s' % (os.path.basename (self.document.name))

templates/tasks/comments.html
<style ="text/css" >

#main_comments_box
{
// Commented this out cos it was introducing a tall empty box
// position:relative;
// left:-20px;
// top:50px;
// width:600px;
// border 1px solid gray;
// height:110%;
}

.comment_box
{
position:relative;
left:40px;
width:500px;
min-height:70px;
border-top:1px solid gray;
//padding:2px;
}

.comment_string
{

color:black;
}
.each_comment
{
position:absolute;
left:55px;
top:8px;
font-size:13.5px;
line-height:1.4;
word-wrap:break-word;
font-style:arial,sans-serif;
}


.commenter_name
{
display:inline;
color:blue;
text-decoration:none;

}

.comment_photo_box
{
position:absolute;
left:20px
top:25px
min-height:40px;
min-width:40px;
padding:8px;
}

.comment_date

{
color:#999999;
font-size:13px;
position:relative;
top:5px;
}
#no_comments_word
{
font-size:19px;
color:gray;
padding:5px;
position:relative;
top:30px;

}
</style>

{% comment %}
{% if is_task_comment %}
<h2>Task - {{ curr_object.subject }}</h2>
{% else %}
<h2>Subtask - {{ curr_object.subject }}</h2>
{% endif %}
{% endcomment %}

{# Display existing comments #}
<div id="main_comments_box">
	{% if comments %}
	<br />
	<div id ="comments_word" style="
	font-size:20px;
	font-weight:400;
	position:relative;
	left:30px;	
	padding:2px;
	">
	Comments</div>
	<table>
	  {% for comment in comments %}
	  <tr>
	  <div class="comment_box">
	  
	  <div class="comment_photo_box">
	 <img src=" " style="
	 width:40px;
	 height:40px;"
	 ></img>
	  </div>
		  <div class="each_comment">
		  <a href="{% url tasks.views.display_portal owner_name=comment.author.get_profile.user.username %}" class="commenter_name">
		    {{ comment.author.get_profile.name }}-
		  </a>
		    <span class="comment_string">
		    {{ comment.comment_string }}
		    </span>
		    
		    <div class="comment_date">
		    {{ comment.time_stamp|date:"P D d M" }}
		   </div>
		   </div>
	  </div>
	  
	  </tr>
	  {% endfor %}
	</table>
	{% else %}
	<div id="no_comments_word">
	There are no Comments yet
	</div>
	{% endif %}


</div>
{# Comment Form #}
{% if not is_visitor and comment_form %}
{% if comment_status == 'Success' %}
<h4> Comment Successfully Added </h4>
{% endif %}

{% comment %}
{% if comment_status == 'Not Found' %}
{% if is_task_comment %}
<h2> No Such Task Exists </h2>
{% else %}
<h2> No Such Subtask Exists </h2>
{% endif %}
{% endif %}
{% endcomment %}

<h2>Add a comment</h2>
<table>
  {{ comment_form }}
</table>
{% endif %}

templates/tasks/display_task.html
{% extends "base_portal.html" %}

{% block title %}
{{ block.super }} 
Task
{% endblock title %}

{% block display_stuff %}

<style type="text/css">

  table.edit_subtask_table th
  {
  padding:0px;
  background-color:;
  color:#800517;
  }


  table.edit_subtask_table 
  {

  position:relative;
  left:0px;
  }

  .edit_subtask_main
  {

  position:relative;
  left:395px;
  top:-23px;
  border:1px solid #999999;
  width:300px;

  }

  #task_from_dept
  {
  <span class="subtask_creation_date">
    {{ curr_subtask.creation_date|date:"P D dS M "  }} 
  </span>


  position:relative;
  top:15px;
  padding: 10px 10px;
  left:8px;
  color:#2B3856;
  font-size:16px;
  width:30px;
  }

  #task_to_dept
  {
  position:relative;
  top:15px;
  padding: 10px 10px;
  left:235px;
  color:#2B3856;
  font-size:16px;

  }



  #task_heading
  {
  position:relative;
  top:22px;
  text-align:center;
  background-color:#2599FF;
  font-style:sans-serif;
  height:50px;

  }


  #go_to_task
  {
  font-size:100%;
  position:absolute;
  left:380px;
  top:10px;
  display:none;
  }



  #task_deadline
  {
  position:relative;
  top:14px;
  left:190px;
  color:#7E3117;
  font-size:19px;
  }

  #task_status
  {
  position:relative;
  top:30px;
  left:397px;
  color:#AF7817;
  font-size:20px;
  font-weight:italic,bold;
  }

  #task_creation_date
  {
  font-size:13px;
  color:#999980;

  }

  /*new*/


  #task_word
  {
  font-weight:400px;
  color:#302217;
  font-size:32px;
  position:absolute;
  left:280px;
  top:10px;
  }



  #task_proposer
  {
  display:inline;
  padding:10px;
  position:relative;
  top:35px;
  left:59px;
  font-size:22px;
  font-weight:500;
  width:230px;
  color:#8D38C9;
  }


  #des_of_task
  {
  position:relative;
  text-indent:40px;
  padding-top:8px;
  padding-left:18px;
  margin-bottom:15px;
  margin-top:6px;
  top:70px;
  left:60px;
  width:550px;
  height:auto;
  min-height:70px;
  border:1.5px solid #827839;
  //background-color:#643289;
  font-size:90%;
  color:#153E7E;
  }

  #task_subject
  {
  position:relative;
  top:53px;
  left:70px;
  font-size:20px;
  }

  #disp_task_box
  {
  position:relative;
  top:10px;
  left:-1px;
  width:700px;
  background-color:#F1FFFF;
  border:2px solid blue;
  min-height:450px;
  padding:0px;
  color:blue;
  }


</style>





<div id="disp_task_box">
  {% if is_owner %}
  <a href="{% url tasks.views.edit_task task_id=curr_task.id owner_name=page_owner %}">Edit Task</a>
  {% endif %}

  
  <span id="task_from_dept"> 
    From-
          <a href="{% url tasks.views.display_department_portal owner_name=curr_task.creator.get_profile.user.username %}" style="text-decoration:none;">{{ curr_task.creator.get_profile.get_dept }}  Department </a> 
  </span>
  
  <div id="task_heading">
    <div id="task_word">
      Task
    </div>
    <span id="task_deadline">
      Deadline:
      {{ curr_task.deadline|date:"D d N"  }} 
    </span>
  </div>


  <div id="task_status">
    Status:
    {{ curr_task.status }} 
  </div>
  
  <div id="tasks_propser_pic">
  </div>
<div id="task_proposer">

    Proposer:
      <a href="{% url tasks.views.display_portal owner_name=curr_task.creator.get_profile.user.username %}" style="text-decoration:none;"> {{ curr_task.creator.get_profile.name }}
</a>
    <span id="task_creation_date">
      {{ curr_task.creation_date|date:"P D dS M "  }} 
    </span>

  </div>
  
  <div id="task_subject">
    Subject:{{ curr_task.subject }}
  </div>

  <div id="des_of_task">
    <span id="description_word"  style="
					font-size:16px;
					color:black;
					">
      Description-
    </span>
    {{ curr_task.description }} 
  </div>



  {% include "tasks/comments.html" %}
</div>



{% for curr_subtask in curr_task.subtask_set.all %}
<br />
{% with curr_subtask.subtaskcomment_set.all as comments %}
<a href="{% url tasks.views.display_subtask subtask_id=curr_subtask.id owner_name=page_owner %}">View separately</a>
{% include "tasks/subtask_template.html" %}
{% endwith %}
{% endfor %}
{% endblock display_stuff %}

templates/tasks/display_updates.html
{% if updates %}
<table class="sortable" id="updates_table" cellpadding="0" cellspacing="0">
  <tr>
    <th>Message</th>
    <th>Time</th>
    {% if po_is_core %}
    <th>Author</th>
    {% endif %}
  </tr>
  {% for update in updates %}
  <tr>
    <td> {{ update.comment_string }} </td>
    <td> {{ update.time_stamp }} </td>
    {% if po_is_core %}
    <td> {{ update.author.get_profile.name }} </td>
    {% endif %}
  </tr>
  {% endfor %}
</table>
{% else %}
<h4>No Updates Yet</h4>
{% endif %}

templates/tasks/edit_task.html
<script type="text/javascript">


  function submit_dissapear()
  {
  alert("hey");
  $("div.submit_botton_dissapear").hide();

  }

</script>
<style type="text/css">
  .submit_botton_dissapear
  {
  //position:fixed;
  float:top;
  float:left;
  }
</style>

{% extends "base_portal.html" %}

{% block title %}
{{ block.super }} 

{% if is_new_task %}
Create a New Task
{% else %}
Edit Task
{% endif %}
{% endblock title %}

{% block form_stuff %}
<div align="center">
  <div class="rbroundbox"> 
    <div class="rbtop">
      <div>
	<div>
	</div>
      </div>
    </div>
    <div class="rbcontentwrap"> 
      <div class="rbcontent"> 
	{% if is_new_task %}
	<h2>Create a New Task</h2>
	{% else %}
	<h2>Edit Task</h2>
	{% endif %}
      </div>
    </div>
    <!-- /rbcontent --> 
    <div class="rbbot">
      <div>
	<div>
	</div>
      </div>
    </div> 
  </div>
  <!-- /rbroundbox --> 

  {# The Template Form (hidden) #}
  <div class="template-form">
    <div class="rbroundbox">
      <div class="rbtop">
      	<div>
      	  <div>
      	  </div>
      	</div>
      </div>
      <div class="rbcontentwrap">
      	<div class="rbcontent">
	  {% with template_form as form %}
	  {% include "tasks/subtask_form.html" %}
	  {% endwith %}
	  {% comment %}
	  {% if not forloop %}
	  {% endif %}
	  {% endcomment %}
    	</div>
      </div>
      <!-- /rbcontent -->
      <div class="rbbot">
    	<div>
    	  <div>
    	  </div>
    	</div>
      </div>
    </div>
    <!-- /rbroundbox  -->
  </div>

  <form method="POST" action="" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="rbroundbox">
      <div class="rbtop">
	<div>
    	  <div>
    	  </div>
	</div>
      </div>
      <div class="rbcontentwrap">
	<div class="rbcontent">
	  <table>
	    {% if is_new_task %}
	    <tr>
	      <th>Department: </th>
	      <td>{{ user_dept_name }} </td>
	    </tr>
	    <tr>
	      <th>Creator: </th>
	      <td>{{ user_name }} </td>
	    </tr>
	    {% else %}
	    <tr>
	      <th>Department: </th>
	      <td>{{ curr_task.creator.get_profile.get_dept }} </td>
	    </tr>
	    <tr>
	      <th>Creator: </th>
	      <td>{{ curr_task.creator.get_profile.name }} </td>
	    </tr>
	    {% endif %}
	    {{ task_form.as_table }}
	    <!-- CHANGE THIS -->
	    {{ tagfs }}
	  </table>
	</div>
      </div>
      <!-- /rbcontent --> 
      <div class="rbbot">
	<div>
	  <div>
	  </div>
	</div>
      </div> 
    </div>
    <!-- /rbroundbox --> 

    {% include "tasks/comments.html" %}

    {% comment %}
    {% if not is_new_task %}
    {% endif %}
    
    {% endcomment %}
    {% include "tasks/document_upload.html" %}

    <div class="rbroundbox"> 
      <div class="rbtop">
	<div>
	  <div>
	  </div>
	</div>
      </div>
      <div class="rbcontentwrap"> 
	<div class="rbcontent"> 
	  <h2>Subtasks</h2>
	  <!-- <p>Fill as many Subtasks as you want</p> -->
	</div>
      </div>
      <!-- /rbcontent --> 
      <div class="rbbot">
	<div>
	  <div>
	  </div>
	</div>
      </div> 
    </div>    
    <!-- /rbroundbox -->

    {{ subtaskfs.management_form }}
    {% for form in subtaskfs.forms %}

    <div class="visible-form">   
      <div class="rbroundbox">
	<div class="rbtop">
    	  <div>
    	    <div>
    	    </div>
    	  </div>
	</div>

	<div class="rbcontentwrap">
    	  <div class="rbcontent">
	    {% include "tasks/subtask_form.html" %}
    	  </div>
	</div>
	<!-- /rbcontent -->
	<div class="rbbot">
    	  <div>
    	    <div>
    	    </div>
    	  </div>
	</div>
      </div>
      <!-- /rbroundbox --> 
    </div>

    {% with form.instance.subtaskcomment_set.all as comments %}
    {% include "tasks/comments.html" %}
    {% endwith %}


    {% endfor %}

    <a href="#" id="add">Add a SubTask</a>

    <table>
      <tr>
	<td>
	  <div class="submit_button_dissapear">
	    {% if is_new_task %}
	    <input type="submit" name = "Create" value="Create"  onclick="submit_dissapear_edittask()" />
	    {% else %}
	    <input type="submit" name = "Edit" value= "Submit" />
	    {% endif %}
	  </div>
	</td>
	<td>
	  <input type="hidden" name="next" value="../../home" />
	</td>
      </tr>
    </table>
  </form>
</div>

{% endblock form_stuff %}

{% block javascript_stuff %}

<script type="text/javascript" src="{{ MEDIA_URL }}js/dynamic-formset.js">
</script>
<!-- <script type="text/javascript" src="http://www.shaastra.org/2011/media/main/autocomplete/jquery.bgiframe.min.js"> -->
<!-- </script> -->
<!-- <script type="text/javascript" src="http://www.shaastra.org/2011/media/main/autocomplete/jquery.dimensions.js"> -->
<!-- </script> -->
<!-- <script type="text/javascript" src="http://www.shaastra.org/2011/media/main/autocomplete/jquery.autocomplete.js"> -->
<!-- </script> -->
<script type="text/javascript">
  var subject_data = {{ subject_data_js|safe }}
  $ (document).ready (function (){
  $ ("#id_subject").autocomplete (subject_data);
  });
</script>
{% endblock javascript_stuff %}

templates/tasks/subtask_form.html
<div class="subtask-heading">
  {# 0 for Template form. Else, forloop.counter #}
  Subtask {% if forloop %} {{ forloop.counter }} {% else %} 0 {% endif %} 
</div>
<table>
  {% for field in form.visible_fields %}
  {% if field.label != 'Delete' %}
  <tr>
    <th>{{ field.label_tag }}</th>
    <td>
      {{ field.errors }}
      {{ field }} 
    </td>
  </tr>
  {% else %}
  <div class="delete-checkbox">
    {{ field.label_tag }}
    {{ field }}
  </div>
  {% endif %}
  {% endfor %}

  {% for field in form.hidden_fields %}
  {{ field }} 
  {% endfor %}
</table>
<p>
  <a href="#" class="delete">Delete this SubTask</a>
</p>

<!-- <style type="text/css"> -->
<!--   .subtask-heading1 -->
<!--   { -->

<!--   position:relative; -->
<!--   display:inline; -->
<!--   font-size:25px; -->
<!--   font-weight:bold;	 -->

<!--   } -->
<!--   .image_subtask_slide -->
<!--   { -->
<!--   -webkit-border-radius: 7px; -->
<!--   -moz-border-radius: 7px;  -->
<!--   position:relative; -->
<!--   padding:10px; -->
<!--   background-color:#Efffff; -->
<!--   border:2px solid gray; -->
<!--   height:50px;	 -->
<!--   } -->
<!--   .subtask_form_subject -->
<!--   { -->
<!--   position:absolute; -->
<!--   left:10px; -->
<!--   color:blue; -->
<!--   font-size:16px; -->
<!--   } -->

<!--   .subtask_form_deadline -->
<!--   { -->
<!--   position:absolute; -->
<!--   top:40px; -->
<!--   right:20px; -->
<!--   display:block-inline; -->
<!--   color:#777777; -->
<!--   font-size:15px; -->
<!--   } -->
<!--   .subtask_slide -->
<!--   { -->
<!--   position:absolute; -->
<!--   right:40px; -->
<!--   width:20px; -->
<!--   height:20px; -->
<!--   background-color:red; -->
<!--   } -->
<!--   .show_subtask_form_class -->
<!--   { -->
<!--   border-left:1px solid #999999; -->
<!--   border-right:1px solid #999999; -->

<!--   } -->
<!-- </style> -->

<!-- <script type="text/javascript"> -->

<!--   $("div.image_subtask_slide").hover( function() -->
<!--   { -->
<!--   //		alert("hey"); -->
<!--   $(this).css('background-color','#E0FFFF'); -->
<!--   }, -->
<!--   function() -->
<!--   { -->
<!--   $(this).css('background-color','#FFFFFF'); -->
<!--   }); -->
<!-- </script> -->

<!-- <div class="hide_subtask_slide{{forloop.cunter}}"> -->
<!--   <div class ="image_subtask_slide" id="subtask_slide{{forloop.counter}}"> -->

<!--     <div class="subtask-heading1"> -->
<!--       {# 0 for Template form. Else, forloop.counter #} -->
<!--       {% if forloop %} Subtask {{forloop.counter}}{% else %} Task {% endif %}  -->
<!--     </div> -->
<!--     <span class="subtask_form_deadline"> -->

<!--       {{form.deadline.value}} -->
<!--     </span> -->

<!--     <div class="subtask_form_subject"> -->
<!--       {% if form.subject.value %} -->
<!--       {{form.subject.value}} -->
<!--       {% endif %} -->
<!--     </div> -->
<!--   </div> -->
<!-- </div> -->

<!-- <div id="show_subtask_slide{{forloop.counter}}" class="show_subtask_form_class" > -->
<!--   <table> -->
<!--     {% for field in form.visible_fields %} -->

<!--     {% if field.label != 'Delete' %} -->
<!--     <tr> -->
<!--       <th>{{ field.label_tag }}</th> -->
<!--       <td> -->
<!-- 	{{ field.errors }} -->
<!-- 	{{ field }}  -->
<!--       </td> -->
<!--     </tr> -->
<!--     {% else %} -->
<!--     <div class="delete-checkbox"> -->
<!--       {{ field.label_tag }} -->
<!--       {{ field }} -->
<!--     </div> -->
<!--     {% endif %} -->
<!--     {% endfor %} -->

<!--     {% for field in form.hidden_fields %} -->
<!--     {{ field }}  -->
<!--     {% endfor %} -->
<!--   </table> -->

<!--   <p> -->
<!--     <a href="#" class="delete">Delete this SubTask</a> -->
<!--   </p> -->

<!--   {% with form.instance.subtaskcomment_set.all as comments %} -->
<!--   {% include "tasks/comments.html" %} -->
<!--   {% endwith %} -->
<!-- </div> -->